services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopper_api
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/shopper_api?schema=public
      - TZ=utc
      - GEMINI_API_KEY
    depends_on:
      - db

volumes:
  db_data:
    driver: local
