services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopper_api
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: curl -f http://db:5432
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shopper_api?schema=public&connect_timeout=5000
      - TZ=utc
      - GEMINI_API_KEY
    depends_on:
      - db
    links:
      - db
    networks:
      - default

volumes:
  db_data:
    driver: local

